### PR TITLE
#95: HSSFWorkbook Integration Test

### PR DESCRIPTION
**Pull request by melloware**
#95: Integration Test

### CODE REVIEW

**Comment by melloware** [comment]
The only difference between this integration test and the users bug is I didn't do this...

```java
 Font font = workbook.createFont();
            font.setFontName("黑体");
```

Because I don't have whatever font that is to load and maybe that is the `java.awt` issue?

**Comment by gastaldi** [comment]
That makes sense. It probably falls back to using the AWT API to find the missing font

**Comment by melloware** [comment]
Ok so this boils the issue down to a MacOS issue with Java AWT.

**Comment by gastaldi** [comment]
Can you try running with BellSoft's GraalVM?

**Comment by melloware** [comment]
Maybe @cjbi can I don't have a Mac anymore 😀

**Comment by cjbi** [comment]
> Maybe @cjbi can I don't have a Mac anymore 😀

I didn't use macOS, but used the gitpod provide Linux environment to build. The compile image I used is quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21, and I have already configured the environment there:
https://gitpod.io/new#https://github.com/cjbi/quarkus-poi-bug-report

**Comment by cjbi** [comment]
I used ubuntu-latest, it's also reproducible，there is my Actions:
https://github.com/cjbi/quarkus-poi-bug-report/actions/runs/7648941828

**Comment by melloware** [comment]
@cjbi see my comment on the ticket.

**Pull request closed without merging**
